[package]
name = "example-2-backward-propagation-and"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
neural-net-core = { path = "../../crates/neural-net-core" }
