[package]
name = "example-5-modern-activations"
version = "0.1.0"
edition = "2021"

[dependencies]
neural-net-core = { path = "../../crates/neural-net-core" }
neural-net-types = { path = "../../crates/neural-net-types" }
